### ISSUE TITLE
[Bug] Iterating every other connection instead of every other connection_info.

### ISSUE THREAD

**Issue by ldunhamci** [mikemalinowski/synaptic#1]
https://github.com/mikemalinowski/synaptic/blob/e87e9cc54be5c2c7accf4d0f798e7ba3753ff8ee/synaptic/meta.py#L116C29-L116C45

Currently iterating every other connection, whereas the intent would be to iterate every other connection_info due to the source/dest plugs from the listConnection results.

Tested fixed in Maya 2020 (with Py2 branch).

**Comment by mikemalinowski** [comment]
Nice find ldunham, I have merged in your fix
